version: '3'

services:

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    ports:
     - "8200:80"
     - "8443:443"
    volumes:
     - ./kanboard_data:/var/www/app/data
     - ./kanboard_plugins:/var/www/app/plugins
     - ./kanboard_ssl:/etc/nginx/ssl
    restart: unless-stopped

    